export const metadata = {
  title: "Terms of Service",
};

export default function TermsPage() {
  return (
    <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 py-16">
      <h1 className="text-4xl font-bold text-neutral-800 dark:text-neutral-100">Terms of Service</h1>
      <p className="text-neutral-500 dark:text-neutral-400 mt-2">Last updated: January 2025</p>

      <div className="mt-10 space-y-8 text-neutral-600 dark:text-neutral-300 leading-relaxed">
        <section>
          <h2 className="text-xl font-bold text-neutral-800 dark:text-neutral-100 mb-3">1. Acceptance of Terms</h2>
          <p>By accessing or using CookMate AI, you agree to be bound by these Terms of Service. If you do not agree with any part of these terms, you may not use our service. These terms apply to all visitors, users, and others who access the platform.</p>
        </section>

        <section>
          <h2 className="text-xl font-bold text-neutral-800 dark:text-neutral-100 mb-3">2. User Accounts</h2>
          <p>To access certain features (AI recipe generation, food analysis, recipe creation, favorites), you must create an account. You are responsible for maintaining the confidentiality of your password and for all activities that occur under your account. You must be at least 13 years old to create an account.</p>
        </section>

        <section>
          <h2 className="text-xl font-bold text-neutral-800 dark:text-neutral-100 mb-3">3. User Content</h2>
          <p>You retain ownership of the recipes, reviews, and other content you create on CookMate AI. By posting content, you grant us a non-exclusive, worldwide, royalty-free license to use, reproduce, and display your content within the platform. You represent that you have the right to share any content you post.</p>
        </section>

        <section>
          <h2 className="text-xl font-bold text-neutral-800 dark:text-neutral-100 mb-3">4. AI-Generated Content</h2>
          <p>Recipes and nutritional analyses generated by our AI features are provided for informational and educational purposes only. We do not guarantee the accuracy, completeness, or safety of AI-generated content. Always use your own judgment and consult a professional for dietary or health-related advice. AI-generated recipes are not reviewed by human experts before being displayed.</p>
        </section>

        <section>
          <h2 className="text-xl font-bold text-neutral-800 dark:text-neutral-100 mb-3">5. Food Analysis Disclaimer</h2>
          <p>The AI food analyzer provides estimated nutritional information based on visual analysis. These estimates may not be accurate and should not be used as a substitute for professional nutritional advice, medical guidance, or food safety information. CookMate AI is not responsible for any decisions made based on AI-generated analysis.</p>
        </section>

        <section>
          <h2 className="text-xl font-bold text-neutral-800 dark:text-neutral-100 mb-3">6. Acceptable Use</h2>
          <p>You agree not to misuse the service, including but not limited to: attempting to gain unauthorized access, using the service for illegal purposes, spamming other users, submitting inappropriate content, or attempting to overwhelm the service with excessive API requests.</p>
        </section>

        <section>
          <h2 className="text-xl font-bold text-neutral-800 dark:text-neutral-100 mb-3">7. Intellectual Property</h2>
          <p>The CookMate AI name, logo, and overall design are our intellectual property. You may not copy, modify, or distribute any part of the platform without our written permission. Community recipes are owned by their respective creators as described in Section 3.</p>
        </section>

        <section>
          <h2 className="text-xl font-bold text-neutral-800 dark:text-neutral-100 mb-3">8. Limitation of Liability</h2>
          <p>CookMate AI is provided &quot;as is&quot; and &quot;as available&quot; without warranties of any kind. We are not liable for any indirect, incidental, special, or consequential damages arising from your use of the service, including but not limited to damages related to AI-generated content accuracy.</p>
        </section>

        <section>
          <h2 className="text-xl font-bold text-neutral-800 dark:text-neutral-100 mb-3">9. Termination</h2>
          <p>We reserve the right to suspend or terminate your account at any time for violations of these terms. You may delete your account at any time by contacting us. Upon deletion, your personal data will be removed in accordance with our Privacy Policy.</p>
        </section>

        <section>
          <h2 className="text-xl font-bold text-neutral-800 dark:text-neutral-100 mb-3">10. Changes to Terms</h2>
          <p>We reserve the right to modify these terms at any time. We will provide notice of significant changes by posting the updated terms on this page. Your continued use of the service after changes constitutes acceptance of the new terms.</p>
        </section>

        <section>
          <h2 className="text-xl font-bold text-neutral-800 dark:text-neutral-100 mb-3">11. Contact</h2>
          <p>For questions about these Terms of Service, please contact us at <a href="mailto:legal@cookmateai.com" className="text-primary-500 hover:underline">legal@cookmateai.com</a> or through our <a href="/contact" className="text-primary-500 hover:underline">Contact page</a>.</p>
        </section>
      </div>
    </div>
  );
}